### ISSUE TITLE
are the weights available? 

### ISSUE THREAD

**Issue by martinbel** [orobix/retina-unet#2]
Hi, 

First of all, great project thanks for open sourcing it! I need to use this model as a preprocessing step for another task therefore it would save me some time to have the weights available. Is there any chance of posting these?

Best, 
Martín

**Comment by dcorti** [comment]
Hi Martin,

Thanks for your interest! 
Yes, the weights are available. The weights relative to the published results are saved in the file `./test/test_best_weights.h5` as HDF5 file.
I must write it in the Readme as well :)

**Comment by AliSaeed86** [comment]
Hi,
Please, i am trying to load the saved weights from `./test/test_best_weights.h5`, but i am getting the below error on this line of code :
`model = model_from_json(open(path_experiment+name_experiment +'_architecture.json').read())`

error msg :
`ValueError: ('Unrecognized keyword arguments:', dict_keys(['input_dtype']))`

Note : i am working on tensorflow 2.6.0, python 3.8.10 

Thanks
