### ISSUE TITLE
BugReport: hard-coded with patchsize

### ISSUE THREAD

**Issue by pythonokai** [orobix/retina-unet#23]
file:    /lib/help_functions
function:    pred_to_imgs
describe:    In line 90, reshape function, shape (pred_images.shape[0],1,48,48)) are hard-coded, I will go wrong when you change patchsize in 'configuration.txt'.
my solution is added patch_height=48,patch_width=48 into that function, and use it to have a flexible shape.

And I don't understand line 363 364 in file /lib/extract_patches.py, is it useless or not?

thank you

**Comment by dcorti** [comment]
You're right, I wrongly left this function hard-coded, I just fixed it by passing the patch_height and patch_width as parameters to the function.

Also the lines you mentioned in /lib/extract_patches.py are actually useless. I removed them.

Thank you very much!
