### ISSUE TITLE
Incompatible with Keras 2

### ISSUE THREAD

**Issue by sumsuddin** [orobix/retina-unet#28]
I was running the repo on keras 1 and it worked fine. Now while upgrading keras from version 1 to 2 some incompatibility issues have arisen. Is there any plan to make it compatible with keras 2

**Comment by dcorti** [comment]
I'm working on it now, I hope to finish within a week or so

**Comment by ch977** [comment]
I get a error:
from keras.utils.visualize_util import plot
 ImportError: No module named visualize_util
I check the keras.utils and find no visualize_util
So, is this a version problem?  Should I use the Keras 1?

**Comment by sumsuddin** [comment]
Yes, Keras 2 pull request is not merged yet.

**Comment by dcorti** [comment]
Sorry, did not have time to fix it. However, thanks to @GlastonburyC now the code is compatible with keras 2
