### ISSUE TITLE
run 'python run_training.py' error

### ISSUE THREAD

**Issue by rockywind** [orobix/retina-unet#32]
when i run 'python run_training.py',the error is:
1. Create directory for the results (if not already existing)
Dir already existing
copy the configuration file in the results folder

2. Run the training on GPU with nohup
**nohup: ignoring input and redirecting stderr to stdout**

**Comment by ch977** [comment]
You should look at the test/test_training.nohup file. It is the log file containing the error of the programme.

**Comment by dcorti** [comment]
If you want to see the output on the screen instead of saving it on the .nohup file,  just set nohup=False in the "configuration.txt" file.
